### ISSUE TITLE
Timeout for SSL POST request

### ISSUE THREAD

**Issue by vmakhaev** [tarantool/curl#3] opened 2016-10-05 20:17 UTC
Code to reproduce status 504:

```lua
local curl = require('curl')
local http = curl.http()
local data = '{"a": "b"}'
local resp = http:sync_request('POST', 'https://z4rx9vsaih.execute-api.us-east-1.amazonaws.com/prod/example', data)
print(resp.code, resp.body)
```

I'm not sure if it's problem with tarantool-curl, but same request works from curl:
```
curl -X POST -d '{"a": "b"}' https://z4rx9vsaih.execute-api.us-east-1.amazonaws.com/prod/example
```

Also, GET and not SSL requests works fine for me.

**Comment by vmakhaev** [comment] 2016-10-07 06:16
Sometimes, I also see status 100 for not SSL requests where `http.client` works fine

**Comment by dedok** [comment] 2016-10-16 21:02
The problem is that your server can't handle Expect: 100-continue, i.e. curl -H "Expect: 100" -v -X P-continueOST -d '{"a": "b"}' https://z4rx9vsaih.execute-api.us-east-1.amazonaws.com/prod/example.

Also I found a bug in the tarantool-curl, this bug is that tarantool-curl is handling some replies wrong from your server.

I added a new option, that option helps you to debug server via CURL trace/verbose mode.

This issue will be closed after then I will have code committed into this repo.

P.S.
Here, you can find more details.

This is original curl
```bash
  1 *   Trying 54.192.98.98...                                                      
  2 * Connected to z4rx9vsaih.execute-api.us-east-1.amazonaws.com (54.192.98.98) port 443 (#0)
  3 * TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256                
  4 * Server certificate: *.execute-api.us-east-1.amazonaws.com                     
  5 * Server certificate: Symantec Class 3 Secure Server CA - G4                    
  6 * Server certificate: VeriSign Class 3 Public Primary Certification Authority - G5
  7 > P-continueOST /prod/example HTTP/1.1^M                                        
  8 > Host: z4rx9vsaih.execute-api.us-east-1.amazonaws.com^M                        
  9 > User-Agent: curl/7.49.1^M                                                     
 10 > Accept: */*^M                                                                 
 11 > Expect: 100^M                                                                 
 12 > Content-Length: 10^M                                                          
 13 > Content-Type: application/x-www-form-urlencoded^M                             
 14 > ^M                                                                            
 15 * upload completely sent off: 10 out of 10 bytes                                
 16 < HTTP/1.1 400 Bad Request^M                                                    
 17 < Server: CloudFront^M                                                          
 18 < Date: Sun, 16 Oct 2016 20:56:45 GMT^M                                         
 19 < Content-Type: text/html^M                                                     
 20 < Content-Length: 551^M                                                         
 21 < Connection: close^M                                                           
 22 < X-Cache: Error from cloudfront^M                                              
 23 < Via: 1.1 8ddad0bbc4c65b2ed58c8c2d64ea3668.cloudfront.net (CloudFront)^M       
 24 < X-Amz-Cf-Id: OpPuRvzJ3qYVGLsGFo_f4U6a1EZmjZmRWTPmJ52WM0zkccemrFls7w==^M       
 25 < ^M                                                                            
 26 * Closing connection 0  
```

This is tarantool-curl (Source codes are not into the repo yet,  I will do a push tomorrow)
``` bash
 1 * About to connect() to z4rx9vsaih.execute-api.us-east-1.amazonaws.com port 443 (#0)
  2 *   Trying 54.192.13.217...                                                     
  3 * Connected to z4rx9vsaih.execute-api.us-east-1.amazonaws.com (54.192.13.217) port 443 (#0)
  4 * Initializing NSS with certpath: sql:/etc/pki/nssdb                            
  5 *   CAfile: /etc/pki/tls/certs/ca-bundle.crt                                    
  6   CApath: none                                                                  
  7 * SSL connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256                    
  8 * Server certificate:                                                           
  9 *   subject: CN=*.execute-api.us-east-1.amazonaws.com,O="Amazon.com, Inc.",L=Seattle,ST=Washington,C=US
 10 *   start date: Jun 08 00:00:00 2016 GMT                                        
 11 *   expire date: Jul 08 23:59:59 2017 GMT                                       
 12 *   common name: *.execute-api.us-east-1.amazonaws.com                          
 13 *   issuer: CN=Symantec Class 3 Secure Server CA - G4,OU=Symantec Trust Network,O=Symantec Corporation,C=US
 14 > POST /prod/example HTTP/1.1^M                                                 
 15 Host: z4rx9vsaih.execute-api.us-east-1.amazonaws.com^M                          
 16 Accept: */*^M                                                                   
 17 Content-Length: -1^M                                                            
 18 Content-Type: application/x-www-form-urlencoded^M                               
 19 Expect: 100-continue^M                                                          
 20 ^M                                                                              
 21 < HTTP/1.1 400 Bad Request^M                                                    
 22 < Server: CloudFront^M                                                          
 23 < Date: Sun, 16 Oct 2016 21:01:12 GMT^M                                         
 24 < Content-Type: text/html^M                                                     
 25 < Content-Length: 551^M                                                         
 26 < Connection: close^M                                                           
 27 < X-Cache: Error from cloudfront^M                                              
 28 < Via: 1.1 190389384a32aa3a7b18a5ed211cd780.cloudfront.net (CloudFront)^M       
 29 < X-Amz-Cf-Id: JwTczntf65kcq75oIEOjJ5UXR82QG87zTuZdGD8LbJXIQhBik9DE8A==^M       
 30 < ^M                                                                            
 31 * Closing connection 0                                                          
 32 ./tests/bugs.lua: entering the event loop
```

**Comment by dedok** [comment] 2016-10-16 21:08
And, Also, the problem with timeout has fixed. Now you can expect that tarantool-curl returns errors - I mean It will tomorrow :)

**Comment by vmakhaev** [comment] 2016-10-16 21:17
@dedok cool, thanks

**Comment by dedok** [comment] 2016-10-16 21:46
I've pushed - I'll close this tomorrow

**Comment by dedok** [comment] 2016-10-17 09:43
@vmakhaev Hi! Could you test this again? After that I'll close this issue.

**Comment by vmakhaev** [comment] 2016-10-17 10:06
@dedok I will test today or tomorrow

**Comment by dedok** [comment] 2016-10-17 20:21
@vmakhaev thanks for private message with OK! I'm closing this

**Closed by dedok** 2016-10-17 20:21 UTC
